### ISSUE TITLE
Log4j2 error with Spring Boot project

### ISSUE THREAD

**Issue by maikeldus** [tobciu/NotifyMyAndroidLib#1]
Hi, I'm using your library in combination with a Spring boot project but I get the following error:

```
ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console..
```

I'm using Log4j2 myself (in gradle: `compile('org.apache.logging.log4j:log4j:2.3')`). The error makes no sense to me, can you help me?

**Comment by tobciu** [comment]
Hello maikeldus,
log4j2 is designed so that 2 libraries are needed:
- 'log4j-api' 
- 'log4j-core'
(see http://logging.apache.org/log4j/2.x/ )
The implementation is seperated from the API, so you dont need to use log4j2 because the library using it.

to solve your problem, you have to add the log4j2-core to your project (see https://logging.apache.org/log4j/2.x/maven-artifacts.html#Using_Log4j_in_your_Gradle_build )

I've updated this library and added the missing log4j2-core library to the pom.xml. also i've updated the versions of the dependencies, please use this new version 1.0.2 
http://search.maven.org/#artifactdetails%7Cde.tobj.nma%7Cnmaclient%7C1.0.2%7Cjar

:-)

**Comment by maikeldus** [comment]
Thanks! Works now
